apiVersion: v1
kind: ResourceQuota
metadata:
  name: backend-quota
  namespace: backend-ns
spec:
  hard:
    # HPA 최대 10 Pod * 300m Limit = 3 Core. 여유 있게 4 Core 제한.
    limits.cpu: "4"
    # HPA 최대 10 Pod * 328Mi Limit = 3.2 GiB. 여유 있게 6 GiB 제한.
    limits.memory: "6Gi"
    # HPA 최대 10 Pod * (100m+50m Request) = 1.5 Core. 여유 있게 2 Core 제한.
    requests.cpu: "2"
    # HPA 최대 10 Pod * (100Mi+64Mi Request) = 1.64 GiB. 여유 있게 3 GiB 제한.
    requests.memory: "3Gi"
    pods: "15" # HPA 최대 10개 + 여유분
    services: "5"