apiVersion: v1
kind: LimitRange
metadata:
  name: frontend-limits
  namespace: frontend-ns
spec:
  limits:
  - default:
      cpu: 200m
      memory: 200Mi
    defaultRequest:
      cpu: 100m
      memory: 100Mi
    max:
      cpu: 500m # 최대 0.5 Core 이상 사용 금지
      memory: 512Mi # 최대 512Mi 이상 사용 금지
    type: Container