apiVersion: v1
kind: ResourceQuota
metadata:
  name: backend-quota
  namespace: backend-ns
spec:
  hard:
    requests.cpu: "1500m"
    requests.memory: "500Mi"
    limits.cpu: "2500m"
    limits.memory: "1Gi"
    services: "10"
    persistentvolumeclaims: "5"
